
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace LightVoting
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.UsbClientSP usbClientSP;
        Gadgeteer.Modules.GHIElectronics.Button button;
        Gadgeteer.Modules.GHIElectronics.Button button1;
        Gadgeteer.Modules.GHIElectronics.Ethernet_J11D ethernet_J11D;
        Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            usbClientSP = new GTM.GHIElectronics.UsbClientSP(1);
		
            button = new GTM.GHIElectronics.Button(4);
		
            ethernet_J11D = new GTM.GHIElectronics.Ethernet_J11D(7);
		
            button1 = new GTM.GHIElectronics.Button(11);
		
            display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, Socket.Unused);

        }
    }
}
